### PR TITLE
perf: Remove needless `while True` loop

### PR DESCRIPTION
**Pull request by Om1609**
The while True loop made no sense, as it was being `return`ed out of in the first iteration itself.

Signed-off-by: Om <92863779+Om1609@users.noreply.github.com>

## PR Type

- [x] This PR improves the code (speed/style improvements or refactoring).
- [ ] This PR fixes an issue.
- [ ] This PR makes an addition to the library (new file, class, method, parameters, etc.).
- [ ] This PR makes a breaking change (renaming/removing parameters, methods, etc.).
- [ ] This PR doesn't make any code changes to the library (documentation, examples).

## Checklist

- [ ] I have searched all pull requests for duplicates.
- [ ] I have tested the changes made.
  - [ ] I have properly changed the docs to reflect the changes made.
- [ ] If 'type: ignore' comments were used, a comment is left to explain why it is needed.

### CODE REVIEW

**Comment by VincentRPS** [comment]
The while loop was not done to loop over things, but rather block anything else from happening during when the bot is shutting down

**Comment by Om1609** [comment]
I'm pretty sure a while true loop does not guarantee that. You rather need asyncio mutex locks `asyncio.Lock`

**Comment by VincentRPS** [comment]
> I'm pretty sure a while true loop does not guarantee that. You rather need asyncio mutex locks `asyncio.Lock`

No it does. The `while` blocks the thread only executing what's inside of the loop, essentially blocking anything else from happening before we've closed everything that's needed to be

**Review by Lulalaby — APPROVED** [review]

**Comment by Lulalaby** [comment]
https://discord.com/channels/881207955029110855/883236900171816970/1059363944252329984

**Review by VincentRPS — APPROVED** [review]

**Pull request merged**
