### PR TITLE
feat: native voice implementation

### PR DESCRIPTION
**Pull request by VincentRPS**
## Summary

Adds a native Python Voice Implementation as a defacto base for any other Voice Implementations, like our future Rust one.

## PR Type

- [ ] This PR improves the code (speed/style improvements or refactoring).
- [ ] This PR fixes an issue.
- [x] This PR makes an addition to the library (new file, class, method, parameters, etc.).
- [ ] This PR makes a breaking change (renaming/removing parameters, methods, etc.).
- [ ] This PR doesn't make any code changes to the library (documentation, examples).

## Checklist

- [x] I have searched all pull requests for duplicates.
- [ ] I have tested the changes made.
  - [ ] I have properly changed the docs to reflect the changes made.
- [x] If 'type: ignore' comments were used, a comment is left to explain why it is needed.

### CODE REVIEW

**Comment by VincentRPS** [comment]
> Would you be implementing voice receiving option?

Yes

**Comment by sairam4123** [comment]
> > Would you be implementing voice receiving option?
> 
> Yes

How do you think of the API? Like can I get an idea of how api will be if it is completed? like you did for voice sending! Also, why voko btw?

**Comment by VincentRPS** [comment]
> > > Would you be implementing voice receiving option?
> > 
> > 
> > Yes
> 
> How do you think of the API? Like can I get an idea of how api will be if it is completed? like you did for voice sending! Also, why voko btw?

`voko` is just a name I like setting for some voice-related stuff, the name won't be used anywhere internally though.

As for the API, I have a good idea for it

```py
# per_packet dispatches a PACKET_RECEIVE event with the decoded voice/packet data,
# useful for AI and other such which would need packets in real-time
voice = await channel.connect(per_packet=False)

# blocks asynchronously until completed, via await voice.complete()
await voice.block(decoder)

# blocks until a single voice packet is received
await voice.get(decoder)

# lets you return and calls `func` when done
# then anything after func is either args or kwargs which are injected
# into the `func`
await voice.wait(decoder, func, channel=channel)

return
```

**Comment by sairam4123** [comment]
Btw, is this no longer planned?

**Comment by VincentRPS** [comment]
> Btw, is this no longer planned?

This, and the other PRs are still primarily planned. I have just closed them because v3 is getting a rewrite, and in their current state they are of no use.

**Pull request closed without merging**
