### PR TITLE
State core.py Refactor

### PR DESCRIPTION
**Pull request by TrapDrap**
Signed-off-by: TrapDrap <69605288+TrapDrap@users.noreply.github.com>

## Summary

Refactor for core.py
- Improves performance by not making 22 elif checks, and using list comprehension in possible places
- Improves logic, splits the main function into smaller ones
- Improves readability (debatably)
- Replaces default python variable "type" being overridden to "event_type"

This is untested code, but it should work. I'm submitting this PR first, if the idea is approved, I will make sure it properly function.

## Checklist

- [x] This PR has breaking changes
- [ ] This PR fixes an issue
- [ ] This is **not** a code change
- [ ] If code changes were made they have been tested
- [ ] I have properly changed the docs to appeal to this change

### CODE REVIEW

**Comment by baronkobama** [comment]
The diff shown shows the entire file as modified, so I can't exactly see the changes made

**Comment by TrapDrap** [comment]
> The diff shown shows the entire file as modified, so I can't exactly see the changes made

Because the entire file was changed, other than the docstring and imports lol

**Comment by VincentRPS** [comment]
> The diff shown shows the entire file as modified, so I can't exactly see the changes made

that's because they uploaded it instead of traditionally using git itself

**Review by VincentRPS — APPROVED** [review]
LGTM. Tested and no errors so seems fine

**Pull request merged**
