### PR TITLE
Additions to app. command example, including match case usage.

### PR DESCRIPTION
**Pull request by TheGiga**
Signed-off-by: gigabit- <49173264+TheGiga@users.noreply.github.com>

## Summary
Changed elif spam to switch case.
removed second 'token' word from comment above `bot.run('token')`

also pycharm decided to change spacings a little bit.

## Checklist

- [ ] This PR has breaking changes
- [ ] This PR fixes an issue
- [ ] This is **not** a code change
- [x] If code changes were made they have been tested
- [ ] I have properly changed the docs to appeal to this change

### CODE REVIEW

**Comment by EmreTech** [comment]
There's a lot of other places in the code that use a bunch of `elif` statements. One such place is the state.

**Comment by VincentRPS** [comment]
I don't get why you changed the indents on the parameters, please change them back to what they were before

**Comment by EmreTech** [comment]
> also pycharm decided to change spacings a little bit.

**Comment by TheGiga** [comment]
> > also pycharm decided to change spacings a little bit.

i guess, if pycharm did it... this is better? i think it tries to follow pep8
i can change it back if needed.

**Comment by TheGiga** [comment]
This pr will affect only this example, since it is not a "part of library".
Other possible match case usages should be further discussed and/or implemented in another PR/commit.

**Review by VincentRPS — APPROVED** [review]

**Pull request merged**
